# Generated by Django 3.2 on 2021-04-22 17:56
"""
RLS用のROLEを作成する。このマイグレーションは、テナント追加前に1度だけ実行する
"""

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        # データ投入より先に必要なロールを作成
        migrations.RunSQL(
            f"CREATE ROLE {settings.RLS_ROLE_NAME};",
            reverse_sql=f"DROP ROLE {settings.RLS_ROLE_NAME};"
        ),
    ]
