# Generated by Django 3.2 on 2021-04-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        # データ投入より先に必要なロールを作成
        migrations.RunSQL("CREATE ROLE tenantuser;"),
        # アプリからデータアクセスを許可する（django_session, django_admin_logは必須）
        migrations.RunSQL("""
            GRANT select, insert, delete ON django_session TO tenantuser;
            GRANT select, insert ON django_admin_log TO tenantuser;
            GRANT select, insert ON django_content_type TO tenantuser;
            GRANT select, insert ON auth_group TO tenantuser;
            GRANT select, insert ON auth_permission TO tenantuser;
        """),
        # FIXME: rollback時のREVOKEも実装しておきたい
    ]
