# Generated by Django 3.2 on 2021-04-22 16:00

from random import choice
from django.db import migrations
from app1.admin import on_create_tenant, on_delete_tenant


def migrate_data(apps, schema_editor):
    Tenant = apps.get_model('app1', 'Tenant')
    TenantUser = apps.get_model('app1', 'TenantUser')
    Customer = apps.get_model('app1', 'Customer')

    # Admin
    TenantUser.objects.create_superuser('admin', password='admin')

    # Tenant1
    t1 = Tenant.objects.create(realm='beproud', name='BeProud Inc.')
    on_create_tenant('', t1, True)
    TenantUser.objects.create_superuser('haru', password='haru', tenant=t1)
    TenantUser.objects.create_superuser('shimizukawa', password='shimizukawa', tenant=t1)

    # Tenant2
    t2 = Tenant.objects.create(realm='cmscom', name='CMS Com')
    on_create_tenant('', t2, True)
    TenantUser.objects.create_superuser('terada', password='terada', tenant=t2)

    # Customers
    for i in range(10):
        t = choice([t1, t2])
        dmy = chr(ord('a')+i)*2
        Customer.objects.create(
            tenant=t,
            **{k: f"{k} {dmy}" for k in ('name', 'address', 'tel', 'email')}
        )


def reverse_data(apps, schema_editor):
    """削除時にはROLEも削除しておく"""
    Tenant = apps.get_model('app1', 'Tenant')
    for obj in Tenant.objects.filter(realm__in=['beproud', 'cmscom']):
        on_delete_tenant('', obj, False)
    Tenant.objects.filter(realm__in=['beproud', 'cmscom']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_setup_roles'),
    ]

    operations = [
        migrations.RunPython(
            migrate_data,
            reverse_code=reverse_data
        ),
    ]
