# Generated by Django 3.2 on 2021-04-22 17:56
"""
RLS用のROLEに対して、全てのテーブルへの全ての権限を許可する。このマイグレーションは、新規のテーブルを追加するたびに実行する必要がある。
"""

from django.db import migrations
from django.conf import settings


def get_grant_sql():
    """GRANT用SQL"""
    # FIXME: このGRANTは新しいテーブルが追加される毎に実行が必要
    sql = f"""
        GRANT ALL ON ALL TABLES IN SCHEMA public TO {settings.RLS_ROLE_NAME};
        GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO {settings.RLS_ROLE_NAME};
    """
    return sql


def get_revoke_sql():
    """REVOKE用SQL"""
    sql = f"""
        REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM {settings.RLS_ROLE_NAME};
        REVOKE ALL ON ALL TABLES IN SCHEMA public FROM {settings.RLS_ROLE_NAME};
    """
    return sql


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_setup_rls_role'),
        ('sessions', '0001_initial'),  # 他のテーブル作成よりも後に実行するため
    ]

    operations = [
        migrations.RunSQL(get_grant_sql(), reverse_sql=get_revoke_sql())
    ]
