# Generated by Django 3.2 on 2021-04-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_datamigration'),
    ]

    operations = [
        # アプリからデータアクセスを許可する（tenant_usersは必須）
        migrations.RunSQL("""
            GRANT select, insert ON tenant_users TO tenantuser;
            GRANT select, insert ON tenants TO tenantuser;
            GRANT select, insert ON customers TO tenantuser;
            GRANT select, insert ON tenant_users_groups TO tenantuser;
            GRANT select, insert ON tenant_users_user_permissions TO tenantuser;
        """),
        # 所属テナントのデータのみを見せたい場合、各テーブルにRLSを設定
        migrations.RunSQL("""
            ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
            CREATE POLICY tenantuser_customers ON customers USING(tenant_id::text = current_user);
            ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
            CREATE POLICY tenantuser_tenants ON tenants USING(id::text = current_user);
            ALTER TABLE tenant_users ENABLE ROW LEVEL SECURITY;
            CREATE POLICY tenantuser_tenantusers ON tenant_users USING(tenant_id::text = current_user);
        """)
        # FIXME: tenant_idをもつテーブル作成時に自動的に適用したい
        # FIXME: rollback時のREVOKEも実装しておきたい
    ]
